### ISSUE TITLE
Team level alerts metrics

### ISSUE THREAD

**Issue by krishnaindani** [cbrgm/opsgenie-exporter#16]
Hi, We have started using this, looks great to get started. But is there plan to add labels for team level metrics which can gives us visibility on alerts count on open, closed etc by teams?

**Comment by Xopherus** [comment]
I've taken a stab at adding support for a team label, as well as priority. Let me know if this is acceptable!

https://github.com/cbrgm/opsgenie-exporter/pull/17

**Comment by cbrgm** [comment]
Hey, sorry for not getting back to this earlier! Will provide a review this weekend, thanks for your contribution! 😊

**Comment by krishnaindani** [comment]
This is awesome, looking forward for it

**Comment by krishnaindani** [comment]
has the changes for this been merged, I saw there was revert?
